config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'dves#index'
  resources :dves

  get 'month_detail', :to => 'dves#month_detail'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dve.rb
class Dve < ApplicationRecord
  before_save :day_kind_values

  belongs_to :user

  validates :event_name, :event_date, :day_kind, presence: true

  enum day_kind: %i[Final_de_semana Dia_de_semana Feriado]

  def day_kind_values
    self.total = 0
    self.total += 20.00 if overnight == true
    self.total += if day_kind == 'Final_de_semana'
                    36.00
                  elsif day_kind == 'Dia_de_semana'
                    18.00
                  else
                    36.00
                  end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :dves
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dves_controller.rb
class DvesController < ApplicationController
  before_action :authenticate_user!

  def index
     @month = params[:date].blank? ? Date.today.month : params[:date][:month]
     @beginning_of_month = Date.parse("1/#{@month}/#{Date.today.year}").beginning_of_month
     end_of_month = @beginning_of_month.end_of_month
     @month_dves = current_user.dves.where('event_date >= ? AND event_date <= ?', @beginning_of_month, end_of_month)
     @total_month = @month_dves.sum(:total).to_f
     @total_count = @month_dves.count
   end

  def new
    @dve = current_user.dves.new
    @dve.event_date = params[:event_date]
  end

  def create
    @dve = current_user.dves.new(dve_params)
    @existing_dve = current_user.dves.find_by(event_date: dve_params[:event_date])

    if @existing_dve
      render :new
      return
    end

    if @dve.save
      redirect_to @dve, notice: 'Dve criada com sucesso!'
    else
      render :new
    end
  end

  def show
    @dve = current_user.dves.find(params[:id])
  end

  def edit
    @dve = current_user.dves.find(params[:id])
  end

  def update
    @dve = current_user.dves.find(params[:id])
    month = @dve.event_date.month
    if @dve.update(dve_params)
      redirect_to month_detail_path(month: month), notice: 'Dve atualizada com sucesso!'
    else
      flash[:alert] = "A erros no preenchimento, não foi possivel atualizar!"
      render :edit
    end
  end

  def destroy
    @dve = current_user.dves.find(params[:id])
    month = @dve.event_date.month
    @dve.destroy

    redirect_to month_detail_path(month: month), notice: 'Dve deletada com sucesso!'
  end

  def month_detail
    @month = params[:month].blank? ? Date.today.month : params[:month]
    @beginning_of_month = Date.parse("1/#{@month}/#{Date.today.year}").beginning_of_month
    end_of_month = @beginning_of_month.end_of_month
    @month_dves = current_user.dves.where('event_date >= ? AND event_date <= ?', @beginning_of_month, end_of_month).order('event_date ASC')
    @total_month = @month_dves.sum(:total).to_f
  end

  private

  def dve_params
    params.require(:dve).permit(:event_name, :event_date, :start_day, :end_day, :overnight, :day_kind, :second_start, :second_end)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dves_helper.rb
module DvesHelper
end

app/views/dves/_app_title.html.erb
<div class="app-title "> 
  <%= link_to  'DveCalculator', root_path %>
</div>

app/views/dves/_form.html.erb
<%= simple_form_for @dve do |f| %>
  <div class="row">
    <div class="input-field col l6 m6 s12">
      <%= f.input :event_date, label: false, placeholder: ("Data do Evento") %>
    </div>
  
    <div class="input-field col l6 m6 s12">
      <%= f.input :event_name, label: false, placeholder: ("Nome do evento") %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col l6 m6 s12">
      <%= f.input :start_day, label: false, placeholder: ("Entrada") %>
    </div>

    <div class="input-field col l6 m6 s12">
      <%= f.input :end_day, label: false, placeholder: ("Saida") %>
    </div>
  </div>

  <div class="row">
    <div class="input-field col l6 m6 s12">
      <%= f.input :second_start, label: false, placeholder: ("Segunda entrada") %>
    </div>

    <div class="input-field col l6 m6 s12">
      <%= f.input :second_end, label: false, placeholder: ("Segunda saida") %>
    </div>
  </div>

    <div class="row">
      <div class="input-field col l6 m6 s12">
        <%= f.input :day_kind, prompt: "Selecione o tipo do dia", label: false %>
      </div>
      
      <div class="switch col l5 offset-l1 m6 s12">
        <%= f.input :overnight %>
      </div>
    </div>
  <div class="row">
    <div class="submit col l12 m12 s12">
      <%= f.button :button %>
    </div>
  </div>
<% end %>

app/views/dves/edit.html.erb
<div class="row">
  <div class="col l7 offset-l3 m8 offset-m2 s12">
    <div class="card">
      <%= render 'app_title' %>
      <div class="already-exists">
          <% if @existing_dve %>
            <div class="message">
              Já existe uma dve para esta data. Deseja editá-la?
              <%= link_to "Clique aqui", edit_dve_path(@existing_dve, dve: {visible: :true}) %>
            </div>
          <% end %>
        </div>
      <div class="card-content">
        <%= render 'form' %>
        <%= link_to 'Voltar', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/dves/index.html.erb
<div class="row less-margin-bottom">
  <div class="col l6 offset-l3 m6 offset-m3 s12">
    <div class="card">
      <%= render 'app_title' %>
      <div class="card-content">
        <%= form_tag(new_dve_path, method: 'get') do %>
          <div class="input-field">
            <%= text_field :event_date, params[:event_date], placeholder: "Selecione uma data",
            class: 'date required form-control picker__input picker__input--active' %>
          </div>
          <div class="submit">
            <%= submit_tag "Cadastrar DVE",
            class: 'waves-effect waves-light btn' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row less-margin-bottom">
  <div class="col l6 offset-l3 m6 offset-m3 s12">
    <div class="card">
      <div class="card-content zero-margin-padding-bottom">
        <%= form_tag(dves_path, method: 'get') do %>
          <div class="input-field">
            <%= select_month(@beginning_of_month) %>
          </div>
          <div class="submit">
            <%= submit_tag "listar valores",
            class: 'waves-effect waves-light btn' %>
          </div>
        <% end %>
        <div class="divider"></div>
        <div class="section zero-margin-padding-bottom">
          <div class="row">
            <div class="col s12">
              <div class="he-dve-titles col s6">
                <span>DVE:</span>
              </div>
              <div class="he-dve-titles col s6">
                <span>H.E:</span>
              </div>
            </div>
            <div class="row zero-margin-padding-bottom">
              <div class="col s12">
                <div class="dve-he-values col s6">
                  <span><%= @total_count %> dias</span>
                  <hr>
                  <span>R$ <%= @total_month %> </span>
                </div>
                <div class="dve-he-values col s6">
                  <span>Soon...</span>
                  <hr>
                  <span>loading...</span>
                </div>
              </div>
            </div>
            <div class="section zero-margin-padding-bottom">
            <div class="divider"></div>
              <div class="month-details">
                <%= link_to 'Clique aqui para mais detalhes do mês',  {:controller => "dves", :action => "month_detail", :month => @beginning_of_month.month } %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/dves/month_detail.html.erb
<h1 class="month-name"><%= I18n.l(Date.parse("#{@month}/1"), format: '%B') %></h1>
  <div class="card">
    <%= render 'app_title' %>
    <div class="card-content">
      <table class="responsive-table highlight">
        <thead>
          <tr>
          <th>Data</th>
          <th>Nome do evento</th>
          <th>Inicio</th>
          <th>Saida</th>
          <th>2° inicio</th>
          <th>2° saida</th>
          <th>Tipo do dia</th>
          <th>pernoite?</th>
          <th>Valor</th>
          <th>Editar?</th>
          <th>Deletar?</th>
        </tr>
        </thead>
        <tbody>
            <% @month_dves.each do |dve| %>
              <tr>
                <td class="dates">
                  <%= I18n.l(dve.event_date, format:"%a - %d/%m") %>
                </td>

                <td class="event_names">
                  <%= dve.event_name %>
                </td>

                <td class="starts">
                  <%= dve.start_day.strftime("%H:%M") %>
                </td>

                <td class="ends">
                  <%= dve.end_day.strftime("%H:%M") %>
                </td>

                <td class="second_starts">
                  <% if dve.second_start.present? %>
                    <%= dve.second_start.strftime("%H:%M") %>
                  <% else %>
                    <span>Não<span>
                  <% end %>
                </td>

                <td class="second_ends">
                  <% if dve.second_end.present? %>
                    <%= dve.second_end.strftime("%H:%M") %>
                  <% else %>
                    <span>Não<span>
                  <% end %>
                </td>

                <td class="day_kind">
                    <%= dve.day_kind.tr('_',' ') %>
                </td>

                <td class="overnight">
                    <%= dve.overnight ? 'Sim' : 'Não' %>
                </td>

                <td class="total">
                  <%= dve.total %>
                </td>

                <td class="edit">
                  <%= link_to edit_dve_path(dve)  do %>
                     <i class="material-icons">edit</i>
                  <% end %>
                </td>

                <td class="delete">
                  <%= link_to dve_path(dve), method: :delete, data: { confirm: "Deseja realmente deletar (#{dve.event_name}?)" }  do %>
                    <i class="material-icons">delete</i>
                  <% end %>
                </td>
              </tr>
            <% end %>
        </tbody>
      </table>
      <%= link_to 'Voltar', root_path %>
    </div>
  </div>

app/views/dves/new.html.erb
<div class="row">
  <div class="col l7 offset-l3 m8 offset-m2 s12">
    <div class="card">
      <%= render 'app_title' %>
      <div class="already-exists">
          <% if @existing_dve %>
            <div class="message">
              Já existe uma dve para esta data. Deseja editá-la?
              <%= link_to "Clique aqui", edit_dve_path(@existing_dve, dve: {visible: :true}) %>
            </div>
          <% end %>
        </div>
      <div class="card-content">
        <%= render 'form' %>
        <%= link_to 'Voltar', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/dves/show.html.erb
<div class="row">
  <div class="col l6 offset-l3 m6 offset-m3 s12">
    <div class="card">
      <%= render 'app_title' %>
      <div class="card-content">
        <div class="row">
          <div class="col m6 s6">
            <span class="field-label">Evento:</span> <%= @dve.event_name %>
          </div>
          <div class="col m6 s6">
            <span class="field-label">Data:</span> <%= I18n.l(@dve.event_date, format: '%a - %d/%m/%Y') %>
          </div>
        </div>
        <div class="row">
          <div class="col m6 s6">
            <span class="field-label">Entrada:</span> <%= @dve.start_day.strftime("%H:%M") %>
          </div>
          <div class="col m6 s6">
            <span class="field-label">Saida: </span> <%= @dve.end_day.strftime("%H:%M") %>
          </div>
        </div>
        <% if @dve.second_start.present? && @dve.second_end.present? %>
          <div class="row">
            <div class="col m6 s6">
              <span class="field-label">Segunda entrada:</span> <%= @dve.second_start.strftime("%H:%M") %>
            </div>
            <div class="col m6 s6">
              <span class="field-label">Segunda saida: </span> <%= @dve.second_end.strftime("%H:%M") %>
            </div>
          </div>
        <% end %>
        <hr class="show-red-bar">
        <div class="row">
          <div class="col m6 s6">
            <span class="field-label">Pernoite:</span>  <%= @dve.overnight ? 'Sim' : 'Não' %>
          </div>
          <div class="col m6 s6">
            <span class="field-label">Total em dve: </span>R$ <%= @dve.total.to_f %>
          </div>
        </div>
        <%= link_to 'Voltar', root_path %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dvecalculator</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <header>
      <%= render 'shared/navbar' %>
    </header>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <footer>
       <%= render "shared/footer" %>
    </footer>

  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
   <nav>
     <div class="nav-wrapper">
       <a href="#!" class="brand-logo">Logo</a>
       <a href="#" data-activates="sidebar" class="button-collapse"><i class="material-icons">menu</i></a>
       <ul class="right hide-on-med-and-down">
         <li><a href="sass.html">Sass</a></li>
         <li><a href="badges.html">Components</a></li>
       </ul>
     </div>
   </nav>
 </div>

 <ul class="side-nav" id="side-bar">
     <li><a href="sass.html">Sass</a></li>
     <li><a href="badges.html">Components</a></li>
  </ul>